/* ================================================================
   GaIA – Base de Conocimientos Educativos
   Currículo completo: Primaria → ESO → Bachillerato
   Organizado por nivel, asignatura y pregunta/respuesta.
   ================================================================ */

// ════════════════════════════════════════════════════════════════
//  PRIMARIA  (6 – 12 años)
// ════════════════════════════════════════════════════════════════

const PRIMARIA = [

  // ── Matemáticas ──────────────────────────────────────────────
  { level: "primaria", subject: "mates", q: "que son los numeros naturales", a: "Los numeros naturales son los que usamos para contar: 0, 1, 2, 3, 4, 5... No tienen decimales ni son negativos. Sirven para contar objetos, personas o cualquier cosa." },
  { level: "primaria", subject: "mates", q: "como se suma con llevadas", a: "Cuando sumas una columna y el resultado tiene dos cifras, escribes la unidad abajo y 'llevas' la decena a la siguiente columna. Ejemplo: 27+15 → 7+5=12, escribes 2 y llevas 1. Luego 2+1+1=4. Resultado: 42." },
  { level: "primaria", subject: "mates", q: "como se resta con llevadas", a: "Si el numero de arriba es menor que el de abajo en una columna, le pides 1 decena prestada al numero de la izquierda. Ejemplo: 43-17 → no puedes 3-7, asi que tomas 1 decena: 13-7=6 y 3-1=3. Resultado: 26." },
  { level: "primaria", subject: "mates", q: "propiedad conmutativa", a: "La propiedad conmutativa dice que el orden no importa al sumar o multiplicar. 3+5 = 5+3 = 8. Y 4×2 = 2×4 = 8. Pero NO funciona con la resta ni la division." },
  { level: "primaria", subject: "mates", q: "que es un numero par e impar", a: "Un numero par se puede dividir entre 2 exacto (termina en 0, 2, 4, 6 u 8). Un numero impar no se puede dividir entre 2 exacto (termina en 1, 3, 5, 7 o 9). Ejemplo: 14 es par, 15 es impar." },
  { level: "primaria", subject: "mates", q: "que es una decena centena millar", a: "Las unidades son los numeros del 1 al 9. Una decena son 10 unidades. Una centena son 100 unidades (10 decenas). Un millar son 1000 unidades (10 centenas). En 3.456: 3 millares, 4 centenas, 5 decenas, 6 unidades." },
  { level: "primaria", subject: "mates", q: "como se multiplica por 10 100 1000", a: "Multiplicar por 10 es anadir un cero al final: 5×10=50. Por 100 son dos ceros: 5×100=500. Por 1000 son tres ceros: 5×1000=5000. Si tiene decimales, mueves la coma a la derecha." },
  { level: "primaria", subject: "mates", q: "que es un numero decimal", a: "Un numero decimal tiene una parte entera y una parte decimal separadas por una coma. Ejemplo: 3,5 es tres unidades y cinco decimas. Las decimas son la primera cifra despues de la coma, las centesimas la segunda." },
  { level: "primaria", subject: "mates", q: "que son las figuras planas", a: "Las figuras planas son formas de 2 dimensiones: triangulo (3 lados), cuadrado (4 lados iguales y 4 angulos rectos), rectangulo (lados opuestos iguales), pentagono (5 lados), hexagono (6 lados), circulo (sin lados, todo curvo)." },
  { level: "primaria", subject: "mates", q: "que son los cuerpos geometricos", a: "Los cuerpos geometricos son figuras en 3D. Tienen largo, ancho y alto. Ejemplos: cubo (6 caras cuadradas), esfera (una pelota), cilindro (un tubo), cono (como un cucurucho), prisma y piramide." },
  { level: "primaria", subject: "mates", q: "unidades de longitud", a: "La unidad principal de longitud es el metro (m). Mas pequenas: decimetro (dm = 0,1 m), centimetro (cm = 0,01 m), milimetro (mm = 0,001 m). Mas grandes: decametro (dam = 10 m), hectometro (hm = 100 m), kilometro (km = 1000 m)." },
  { level: "primaria", subject: "mates", q: "unidades de masa peso", a: "La unidad principal de masa es el gramo (g). Un kilogramo (kg) son 1000 gramos. Un miligramo (mg) es la milesima de gramo. Para cosas muy pesadas usamos la tonelada (t) = 1000 kg." },
  { level: "primaria", subject: "mates", q: "unidades de capacidad litro", a: "La unidad principal de capacidad es el litro (l). Medio litro = 500 mililitros (ml). Un cuarto de litro = 250 ml. Un decilitro (dl) = 100 ml. Una botella de agua grande suele ser 1,5 litros." },
  { level: "primaria", subject: "mates", q: "como se lee la hora en un reloj", a: "En un reloj analogico, la aguja corta marca las horas y la larga los minutos. Cuando la larga esta en el 12 es en punto, en el 3 es y cuarto, en el 6 es y media, en el 9 es menos cuarto. Cada numero entre marcas son 5 minutos." },
  { level: "primaria", subject: "mates", q: "que es la division", a: "La division reparte en partes iguales. Si tienes 12 caramelos y 4 amigos, cada uno recibe 12÷4=3 caramelos. Partes: dividendo (12) ÷ divisor (4) = cociente (3). Si sobra algo, se llama resto." },
  { level: "primaria", subject: "mates", q: "que es una fraccion equivalente", a: "Dos fracciones son equivalentes si representan la misma cantidad. 1/2 = 2/4 = 3/6 = 4/8. Para comprobar, multiplicas en cruz: 1×4 = 2×2 = 4. Para obtenerlas, multiplicas o divides numerador y denominador por el mismo numero." },
  { level: "primaria", subject: "mates", q: "que es la media aritmetica", a: "La media es sumar todos los valores y dividir entre cuantos hay. Ejemplo: notas 7, 8, 6, 9 → suma = 30, hay 4 notas → media = 30÷4 = 7,5. Es como repartir la suma entre todos." },
  { level: "primaria", subject: "mates", q: "que es un porcentaje", a: "Un porcentaje es una fraccion de 100. El 50% significa 50 de cada 100, o sea la mitad. El 25% es un cuarto. Para calcular el 20% de 80: multiplicas 80×20÷100 = 16." },
  { level: "primaria", subject: "mates", q: "tipos de triangulos", a: "Por sus lados: equilatero (3 lados iguales), isosceles (2 lados iguales), escaleno (todos diferentes). Por sus angulos: rectangulo (tiene un angulo de 90°), acutangulo (todos los angulos menores de 90°), obtusangulo (uno mayor de 90°)." },
  { level: "primaria", subject: "mates", q: "que es la proporcionalidad", a: "Dos cantidades son proporcionales cuando al multiplicar una por un numero, la otra se multiplica por el mismo. Ejemplo: si 2 kg de manzanas cuestan 3 euros, 4 kg cuestan 6 euros (el doble de peso, el doble de precio)." },

  // ── Lengua Castellana ────────────────────────────────────────
  { level: "primaria", subject: "lengua", q: "que es un determinante", a: "Los determinantes van delante del sustantivo y lo concretan. Tipos: articulos (el, la, los, las, un, una), demostrativos (este, esa, aquel), posesivos (mi, tu, su, nuestro), numerales (dos, tercero), indefinidos (algun, varios)." },
  { level: "primaria", subject: "lengua", q: "que es un pronombre", a: "Un pronombre sustituye al nombre para no repetirlo. 'Maria come fruta. Ella come fruta.' Ella es un pronombre personal. Otros: yo, tu, el, nosotros, ellos, me, te, se, lo, la, le." },
  { level: "primaria", subject: "lengua", q: "que es un adverbio", a: "Un adverbio modifica al verbo, a un adjetivo o a otro adverbio. Tipos: lugar (aqui, lejos, cerca), tiempo (hoy, ayer, pronto), modo (bien, mal, despacio), cantidad (mucho, poco, bastante), negacion (no, nunca, jamas)." },
  { level: "primaria", subject: "lengua", q: "que son las preposiciones", a: "Las preposiciones unen palabras indicando relacion: a, ante, bajo, cabe, con, contra, de, desde, en, entre, hacia, hasta, para, por, segun, sin, sobre, tras. Ejemplo: 'Voy a casa de mi abuela'." },
  { level: "primaria", subject: "lengua", q: "reglas de acentuacion tildes", a: "Agudas: acento en la ultima silaba, llevan tilde si acaban en vocal, n o s (cafe, cancion). Llanas: acento en la penultima, tilde si NO acaban en vocal, n o s (arbol, lapiz). Esdrujulas: acento en la antepenultima, SIEMPRE llevan tilde (musica, pajaro)." },
  { level: "primaria", subject: "lengua", q: "cuando se escribe con b o con v", a: "Se escribe B: despues de m (tambien), con prefijos bi- sub- (bicicleta), verbos terminados en -bir (escribir, excepto hervir, servir, vivir). Se escribe V: despues de n (invierno), adjetivos terminados en -ivo/iva (activo), despues de ad- (advertir)." },
  { level: "primaria", subject: "lengua", q: "cuando se escribe con h", a: "Se escribe H: palabras que empiezan por hie- hue- (hielo, huevo), formas del verbo haber (hay, ha, he), y del verbo hacer (hago, hice). La h es muda, no se pronuncia." },
  { level: "primaria", subject: "lengua", q: "que es un texto narrativo", a: "Un texto narrativo cuenta una historia. Tiene estructura: introduccion (presenta personajes y lugar), nudo (ocurre el problema o aventura) y desenlace (se resuelve). Ejemplo: cuentos, novelas, fabulas, leyendas." },
  { level: "primaria", subject: "lengua", q: "que es un texto descriptivo", a: "Un texto descriptivo explica como es algo o alguien, usando adjetivos y detalles. Puede describir personas (retrato), lugares (paisaje), objetos o situaciones. Ejemplo: 'Era un bosque oscuro y silencioso, con arboles altisimos'." },
  { level: "primaria", subject: "lengua", q: "que es un texto instructivo", a: "Un texto instructivo da instrucciones paso a paso para hacer algo. Usa verbos en imperativo o infinitivo y numeros para los pasos. Ejemplos: recetas de cocina, instrucciones de un juego, manuales." },
  { level: "primaria", subject: "lengua", q: "que son los prefijos y sufijos", a: "Los prefijos van antes de la raiz de la palabra y cambian su significado: des- (deshacer), in- (invisible), re- (rehacer), pre- (prehistoria). Los sufijos van detras: -ero (panadero), -ista (pianista), -cion (educacion), -mente (rapidamente)." },
  { level: "primaria", subject: "lengua", q: "familias de palabras campo semantico", a: "Una familia de palabras comparte la misma raiz: pan, panadero, panaderia, panecillo, empanar. Un campo semantico agrupa palabras relacionadas por su significado: perro, gato, hamster, canario son del campo semantico de 'mascotas'." },
  { level: "primaria", subject: "lengua", q: "sujeto y predicado de una oracion", a: "El sujeto es quien realiza la accion: ¿Quien? El predicado es lo que se dice del sujeto. Ejemplo: 'Mi hermana (sujeto) juega en el parque (predicado)'. El nucleo del sujeto es un sustantivo y el del predicado es un verbo." },
  { level: "primaria", subject: "lengua", q: "tipos de oraciones segun la intencion", a: "Enunciativas: informan (Hoy llueve). Interrogativas: preguntan (¿Que hora es?). Exclamativas: expresan emocion (¡Que bonito!). Imperativas: ordenan o piden (Cierra la puerta). Desiderativas: expresan deseo (Ojala apruebe). Dubitativas: expresan duda (Quiza venga)." },
  { level: "primaria", subject: "lengua", q: "diptongo e hiato", a: "Diptongo: dos vocales juntas en la misma silaba (ai-re, puen-te, ciu-dad). Se forma con una vocal abierta (a,e,o) + cerrada (i,u) o dos cerradas. Hiato: dos vocales juntas en silabas distintas (le-on, ma-iz, ri-o). Ocurre con dos abiertas o cerrada acentuada + abierta." },

  // ── Ciencias Naturales ───────────────────────────────────────
  { level: "primaria", subject: "naturales", q: "clasificacion de los seres vivos reinos", a: "Los seres vivos se clasifican en 5 reinos: Animal (se mueven, comen otros seres), Vegetal (hacen fotosintesis), Hongos (setas, mohos), Protistas (seres unicelulares como amebas) y Moneras (bacterias)." },
  { level: "primaria", subject: "naturales", q: "animales vertebrados e invertebrados", a: "Los vertebrados tienen esqueleto con columna vertebral: mamiferos, aves, reptiles, anfibios y peces. Los invertebrados no tienen columna: insectos, aracnidos, moluscos (caracol), crustaceos (cangrejo), medusas y gusanos." },
  { level: "primaria", subject: "naturales", q: "tipos de mamiferos", a: "Los mamiferos son animales de sangre caliente que tienen pelo y alimentan a sus crias con leche. Ejemplos: perro, gato, delfin, murcielago (el unico mamifero que vuela), ballena (el mas grande). El ornitorrinco es un mamifero que pone huevos." },
  { level: "primaria", subject: "naturales", q: "tipos de aves", a: "Las aves tienen plumas, pico, ponen huevos y la mayoria vuela. Rapaces: aguila, buho. Acuaticas: pato, pelicano. No voladoras: avestruz, pinguino. Zancudas: flamenco, cigüena. Paseriformes: gorrion, ruisenor." },
  { level: "primaria", subject: "naturales", q: "anfibios y reptiles diferencias", a: "Los anfibios nacen en el agua con branquias y luego desarrollan pulmones (rana, sapo, salamandra). Su piel es humeda. Los reptiles tienen piel con escamas secas, respiran con pulmones desde que nacen (lagartija, serpiente, cocodrilo, tortuga)." },
  { level: "primaria", subject: "naturales", q: "partes de una planta", a: "Raiz: absorbe agua y minerales del suelo y sujeta la planta. Tallo: sostiene la planta y transporta la savia. Hojas: hacen la fotosintesis (producen alimento con luz solar). Flor: organo reproductor. Fruto: protege las semillas." },
  { level: "primaria", subject: "naturales", q: "que es un ecosistema", a: "Un ecosistema es un lugar donde los seres vivos (animales, plantas) conviven con su entorno no vivo (agua, suelo, aire, temperatura). Tipos: bosque, desierto, oceano, rio, pradera, selva tropical, tundra." },
  { level: "primaria", subject: "naturales", q: "cadena alimentaria trofica", a: "Una cadena alimentaria muestra quien come a quien. Los productores (plantas) son comidos por los consumidores primarios (herbivoros como conejos), estos por los secundarios (carnivoros como zorros) y estos por los terciarios (aguila). Los descomponedores (hongos, bacterias) reciclan la materia." },
  { level: "primaria", subject: "naturales", q: "aparato digestivo", a: "La comida entra por la boca, se mastica y mezcla con saliva. Baja por el esofago al estomago, donde los jugos gastricos la deshacen. En el intestino delgado se absorben los nutrientes. En el intestino grueso se absorbe el agua. Los restos salen por el ano." },
  { level: "primaria", subject: "naturales", q: "aparato respiratorio", a: "Al respirar, el aire entra por la nariz o boca, pasa por la laringe y traquea, llega a los bronquios y despues a los pulmones. Alli, en los alveolos, el oxigeno pasa a la sangre y el CO2 sale. El diafragma es el musculo que nos ayuda a respirar." },
  { level: "primaria", subject: "naturales", q: "aparato circulatorio", a: "El corazon bombea la sangre por todo el cuerpo. Las arterias llevan sangre con oxigeno del corazon a los organos. Las venas traen la sangre de vuelta. Los capilares son vasos finisimos donde se intercambian oxigeno y nutrientes con las celulas." },
  { level: "primaria", subject: "naturales", q: "los cinco sentidos", a: "Vista (ojos): vemos colores y formas. Oido (oidos): escuchamos sonidos. Olfato (nariz): olemos. Gusto (lengua): saboreamos dulce, salado, acido, amargo, umami. Tacto (piel): sentimos temperatura, presion, texturas." },
  { level: "primaria", subject: "naturales", q: "estados de la materia cambios", a: "Solido (forma fija), liquido (forma del recipiente) y gas (ocupa todo el espacio). Cambios: fusion (solido→liquido), evaporacion (liquido→gas), condensacion (gas→liquido), solidificacion (liquido→solido), sublimacion (solido→gas directamente)." },
  { level: "primaria", subject: "naturales", q: "fuentes de energia renovable", a: "Las energias renovables no se agotan: solar (del Sol), eolica (del viento), hidraulica (del agua), geotermica (del calor de la Tierra), biomasa (materia organica). Son mas limpias que las no renovables (petroleo, carbon, gas natural) que contaminan y se agotan." },
  { level: "primaria", subject: "naturales", q: "maquinas simples palanca polea", a: "Las maquinas simples facilitan el trabajo. Palanca: una barra que gira sobre un punto fijo (balancin, cascanueces). Polea: una rueda con cuerda para subir peso (pozo). Plano inclinado: una rampa para subir cosas (tobogan al reves). Rueda y eje: reduce la friccion." },
  { level: "primaria", subject: "naturales", q: "alimentacion saludable nutrientes", a: "Una dieta equilibrada incluye: hidratos de carbono (pan, pasta, arroz: dan energia), proteinas (carne, pescado, huevos: ayudan a crecer), grasas saludables (aceite de oliva, frutos secos), vitaminas y minerales (frutas, verduras), agua (al menos 6-8 vasos al dia)." },
  { level: "primaria", subject: "naturales", q: "ciclo del agua", a: "El Sol calienta el agua de mares y rios → se evapora y sube como vapor → al enfriarse se condensa formando nubes → las gotas crecen y caen como lluvia o nieve (precipitacion) → el agua vuelve a rios y mares → y el ciclo se repite sin parar." },

  // ── Ciencias Sociales ────────────────────────────────────────
  { level: "primaria", subject: "sociales", q: "movimiento de rotacion y traslacion tierra", a: "La Tierra hace dos movimientos: Rotacion (gira sobre si misma como una peonza, tarda 24 horas, causa el dia y la noche) y Traslacion (gira alrededor del Sol, tarda 365 dias y 6 horas, causa las estaciones del ano)." },
  { level: "primaria", subject: "sociales", q: "por que hay estaciones del ano", a: "Las estaciones existen porque el eje de la Tierra esta inclinado 23,5°. Cuando el hemisferio norte se inclina hacia el Sol es verano alli e invierno en el sur. Primavera y otono son las transiciones. Por eso en Australia es verano cuando aqui es invierno." },
  { level: "primaria", subject: "sociales", q: "capas de la tierra corteza manto nucleo", a: "La Tierra tiene capas como una cebolla. Corteza: la capa exterior solida donde vivimos (5-70 km). Manto: roca caliente semiliquida debajo (2900 km). Nucleo externo: hierro liquido. Nucleo interno: hierro solido a 5000°C. El centro esta a 6371 km de profundidad." },
  { level: "primaria", subject: "sociales", q: "relieve de espana montanas", a: "La Meseta Central ocupa gran parte de Espana. Cordilleras: Pirineos (norte, frontera con Francia), Cordillera Cantabrica (norte), Sistema Central (divide la Meseta), Sierra Morena (sur de la Meseta), Sistemas Beticos con Sierra Nevada (sur, pico Mulhacen 3479 m, el mas alto de la peninsula)." },
  { level: "primaria", subject: "sociales", q: "rios de espana principales", a: "Vertiente atlantica: Tajo (el mas largo, 1007 km), Duero, Guadiana, Guadalquivir (el mas caudaloso del sur). Vertiente mediterranea: Ebro (el mas caudaloso de Espana), Jucar, Segura. Vertiente cantabrica: rios cortos y caudalosos como el Nervion." },
  { level: "primaria", subject: "sociales", q: "comunidades autonomas de espana", a: "Espana tiene 17 comunidades autonomas y 2 ciudades autonomas (Ceuta y Melilla). Las mas grandes: Castilla y Leon, Castilla-La Mancha, Andalucia. La capital, Madrid, es comunidad y capital de Espana. Cada comunidad tiene su gobierno, parlamento y presidente." },
  { level: "primaria", subject: "sociales", q: "continentes y oceanos del mundo", a: "Los 6 continentes: Europa, Asia, Africa, America (Norte y Sur), Oceania y Antartida. Los 5 oceanos: Pacifico (el mas grande), Atlantico, Indico, Artico (el mas frio) y Antartico (rodea la Antartida)." },
  { level: "primaria", subject: "sociales", q: "climas de espana", a: "Clima oceanico (norte): lluvias todo el ano, temperaturas suaves. Clima mediterraneo (este y sur): veranos calurosos y secos, inviernos suaves. Clima continental (interior): veranos calurosos, inviernos frios. Clima subtropical (Canarias): calido todo el ano. Clima de montana (zonas altas): frio." },
  { level: "primaria", subject: "sociales", q: "sectores economicos primario secundario terciario", a: "Sector primario: obtiene materias primas de la naturaleza (agricultura, ganaderia, pesca, mineria). Sector secundario: transforma materias primas en productos (industria, construccion). Sector terciario: ofrece servicios (comercio, transporte, turismo, sanidad, educacion). En Espana domina el terciario." },
  { level: "primaria", subject: "sociales", q: "prehistoria paleolitico neolitico", a: "Paleolitico: los humanos eran nomadas (se movian buscando comida), cazaban y recolectaban, vivian en cuevas, usaban herramientas de piedra, descubrieron el fuego. Neolitico: inventaron la agricultura y ganaderia, se hicieron sedentarios (vivian en pueblos), fabricaron ceramica y tejidos." },
  { level: "primaria", subject: "sociales", q: "edad antigua romanos en espana", a: "Los romanos conquistaron la peninsula iberica (la llamaban Hispania) hace mas de 2000 anos. Nos dejaron: el idioma (el espanol viene del latin), calzadas (carreteras), acueductos (para llevar agua), puentes, leyes, y ciudades como Merida, Tarragona y Zaragoza." },
  { level: "primaria", subject: "sociales", q: "edad media en espana al andalus reconquista", a: "En el 711, los musulmanes llegaron a la peninsula y crearon Al-Andalus. Su capital, Cordoba, era una de las ciudades mas avanzadas de Europa. Los reinos cristianos del norte fueron recuperando territorio poco a poco (la Reconquista), que termino en 1492 cuando los Reyes Catolicos tomaron Granada." },
  { level: "primaria", subject: "sociales", q: "descubrimiento de america 1492", a: "El 12 de octubre de 1492, Cristobal Colon llego a America con tres carabelas: la Pinta, la Nina y la Santa Maria. Creia haber llegado a las Indias. Los Reyes Catolicos (Isabel y Fernando) financiaron el viaje. Este descubrimiento cambio la historia del mundo." },
  { level: "primaria", subject: "sociales", q: "la constitucion espanola", a: "La Constitucion Espanola de 1978 es la ley mas importante de Espana. Establece que Espana es una monarquia parlamentaria, con un rey como jefe de Estado y un presidente de gobierno. Garantiza derechos como la educacion, la sanidad, la libertad de expresion y la igualdad." },
  { level: "primaria", subject: "sociales", q: "union europea", a: "La Union Europea (UE) es una union de 27 paises europeos. Espana entro en 1986. Compartimos moneda (el euro), podemos viajar y trabajar libremente entre paises miembros. El parlamento europeo esta en Estrasburgo y la Comision Europea en Bruselas." },
  { level: "primaria", subject: "sociales", q: "democracia y elecciones", a: "La democracia es un sistema donde los ciudadanos eligen a sus gobernantes mediante elecciones con voto libre y secreto. En Espana votamos para elegir al Congreso y Senado (elecciones generales), parlamentos autonomicos y ayuntamientos (municipales)." },

  // ── Inglés Primaria ──────────────────────────────────────────
  { level: "primaria", subject: "ingles", q: "partes del cuerpo en ingles", a: "Head (cabeza), eyes (ojos), nose (nariz), mouth (boca), ears (orejas), hair (pelo), shoulders (hombros), arms (brazos), hands (manos), fingers (dedos), legs (piernas), knees (rodillas), feet (pies), toes (dedos del pie)." },
  { level: "primaria", subject: "ingles", q: "familia en ingles", a: "Father/dad (padre), mother/mum (madre), brother (hermano), sister (hermana), grandfather/grandpa (abuelo), grandmother/grandma (abuela), uncle (tio), aunt (tia), cousin (primo/a), son (hijo), daughter (hija)." },
  { level: "primaria", subject: "ingles", q: "comida en ingles food", a: "Bread (pan), rice (arroz), chicken (pollo), fish (pescado), egg (huevo), cheese (queso), milk (leche), apple (manzana), banana (platano), orange (naranja), tomato (tomate), water (agua), juice (zumo)." },
  { level: "primaria", subject: "ingles", q: "ropa en ingles clothes", a: "T-shirt (camiseta), trousers/pants (pantalones), dress (vestido), skirt (falda), jacket (chaqueta), coat (abrigo), shoes (zapatos), boots (botas), socks (calcetines), hat (gorro/sombrero), scarf (bufanda)." },
  { level: "primaria", subject: "ingles", q: "present simple en ingles", a: "El present simple describe rutinas y hechos. I play, you play, he/she plays (anade -s en 3a persona). Negativo: I don't play, he doesn't play. Pregunta: Do you play? Does she play? Ejemplo: 'I play football every Saturday'." },
  { level: "primaria", subject: "ingles", q: "present continuous en ingles", a: "El present continuous describe lo que esta pasando ahora. Se forma con am/is/are + verbo-ing. I am playing, she is reading, they are running. Pregunta: Are you playing? Negativo: I am not playing." },
  { level: "primaria", subject: "ingles", q: "past simple en ingles", a: "El past simple habla del pasado. Verbos regulares anaden -ed: played, walked, watched. Irregulares cambian: go→went, eat→ate, see→saw, have→had, do→did. Pregunta: Did you play? Negativo: I didn't play." },
  { level: "primaria", subject: "ingles", q: "can y can't en ingles", a: "Can expresa habilidad: I can swim (se nadar). Can't es la negacion: I can't fly (no puedo volar). Pregunta: Can you ride a bike? (¿Sabes montar en bici?). Can es igual para todas las personas, no cambia." },
  { level: "primaria", subject: "ingles", q: "comparativos y superlativos en ingles", a: "Comparativo compara dos cosas: big→bigger, small→smaller, beautiful→more beautiful. Superlativo es el maximo: big→the biggest, small→the smallest. Irregular: good→better→the best, bad→worse→the worst." },
  { level: "primaria", subject: "ingles", q: "partes de la casa en ingles house", a: "Kitchen (cocina), bedroom (dormitorio), bathroom (bano), living room (salon), garden (jardin), garage (garaje), door (puerta), window (ventana), roof (tejado), stairs (escaleras), floor (suelo), wall (pared)." },
  { level: "primaria", subject: "ingles", q: "estaciones y tiempo meteorologico en ingles", a: "Seasons: spring (primavera), summer (verano), autumn/fall (otono), winter (invierno). Weather: sunny (soleado), cloudy (nublado), rainy (lluvioso), windy (ventoso), snowy (nevado), hot (caluroso), cold (frio), warm (templado)." },

  // ── Educación Artística ──────────────────────────────────────
  { level: "primaria", subject: "artistica", q: "colores primarios y secundarios", a: "Los colores primarios son rojo, azul y amarillo. No se pueden crear mezclando otros. Al mezclarlos se obtienen los secundarios: rojo+azul=violeta, rojo+amarillo=naranja, azul+amarillo=verde. Los colores complementarios estan enfrente en el circulo cromatico." },
  { level: "primaria", subject: "artistica", q: "colores calidos y frios", a: "Los colores calidos transmiten energia y calor: rojo, naranja, amarillo. Los colores frios transmiten calma y frescor: azul, verde, violeta. En un dibujo, los calidos parecen acercarse y los frios alejarse." },
  { level: "primaria", subject: "artistica", q: "notas musicales", a: "Las 7 notas musicales son: do, re, mi, fa, sol, la, si. Se escriben en un pentagrama (5 lineas). En ingles se usan letras: C, D, E, F, G, A, B. Las notas se repiten en octavas cada vez mas agudas o graves." },
  { level: "primaria", subject: "artistica", q: "familias de instrumentos musicales", a: "Cuerda: guitarra, violin, piano (cuerdas golpeadas), arpa. Viento madera: flauta, clarinete, oboe. Viento metal: trompeta, trombon, tuba. Percusion: tambor, platillos, xilofono, triangulo. Electrofonos: teclado electrico, guitarra electrica." },
  { level: "primaria", subject: "artistica", q: "que es el ritmo y el compas en musica", a: "El ritmo es la organizacion de los sonidos en el tiempo. El compas agrupa los tiempos: un compas de 2/4 tiene 2 tiempos, uno de 3/4 tiene 3 (como el vals), uno de 4/4 tiene 4 (el mas comun en pop y rock). El pulso es el latido constante de la musica." },
];

// ════════════════════════════════════════════════════════════════
//  ESO  –  Educación Secundaria Obligatoria  (12 – 16 años)
// ════════════════════════════════════════════════════════════════

const ESO = [

  // ── Matemáticas ESO ──────────────────────────────────────────
  { level: "eso", subject: "mates", q: "numeros enteros positivos y negativos", a: "Los numeros enteros incluyen los positivos (1, 2, 3...), los negativos (-1, -2, -3...) y el cero. Se representan en una recta numerica. Reglas de signos: (+)(+)=+, (-)(-) =+, (+)(-)=-, (-)(+)=-. Ejemplo: (-3)×(-2)=+6." },
  { level: "eso", subject: "mates", q: "que son los numeros racionales e irracionales", a: "Los racionales se pueden expresar como fraccion a/b: 1/2=0.5, 1/3=0.333... Los irracionales NO se pueden expresar como fraccion y sus decimales no se repiten: π=3.14159..., √2=1.41421... Juntos forman los numeros reales." },
  { level: "eso", subject: "mates", q: "potencias y propiedades", a: "Una potencia es multiplicar un numero por si mismo varias veces: 2³=2×2×2=8. Propiedades: a^m × a^n = a^(m+n), a^m ÷ a^n = a^(m-n), (a^m)^n = a^(m×n), a^0 = 1, a^(-n) = 1/a^n." },
  { level: "eso", subject: "mates", q: "raices cuadradas y cubicas", a: "La raiz cuadrada de un numero es el valor que multiplicado por si mismo da ese numero: √25=5 porque 5×5=25. La raiz cubica: ∛27=3 porque 3×3×3=27. √2≈1.414 (es irracional). Las raices se pueden escribir como potencias fraccionarias: √a = a^(1/2)." },
  { level: "eso", subject: "mates", q: "que es un monomio y polinomio algebra", a: "Un monomio es un producto de un numero y variables: 3x², -5ab. Un polinomio es una suma de monomios: 2x³+5x²-3x+1. El grado es el mayor exponente (aqui 3). Operaciones: sumar/restar terminos semejantes, multiplicar aplicando propiedades de potencias." },
  { level: "eso", subject: "mates", q: "ecuaciones de primer grado", a: "Una ecuacion de primer grado tiene la forma ax+b=c. Para resolverla, aisla la x: pasa los numeros al otro lado cambiando signo. Ejemplo: 3x+5=17 → 3x=17-5 → 3x=12 → x=12/3 → x=4. Comprobacion: 3(4)+5=17 ✓." },
  { level: "eso", subject: "mates", q: "ecuaciones de segundo grado", a: "Forma general: ax²+bx+c=0. Se resuelve con la formula: x = (-b ± √(b²-4ac)) / 2a. El discriminante (b²-4ac) determina las soluciones: si >0 hay 2 soluciones, si =0 hay 1, si <0 no hay solucion real. Ejemplo: x²-5x+6=0 → x=2 y x=3." },
  { level: "eso", subject: "mates", q: "sistemas de ecuaciones metodos", a: "Un sistema de 2 ecuaciones con 2 incognitas se resuelve por: Sustitucion (despejar una variable y sustituir en la otra), Igualacion (despejar la misma variable en ambas e igualar), Reduccion (sumar/restar ecuaciones para eliminar una variable). Ejemplo: x+y=5, x-y=1 → sumando: 2x=6 → x=3, y=2." },
  { level: "eso", subject: "mates", q: "teorema de pitagoras", a: "En un triangulo rectangulo, el cuadrado de la hipotenusa (lado mayor, opuesto al angulo recto) es igual a la suma de los cuadrados de los catetos: c²=a²+b². Si los catetos miden 3 y 4, la hipotenusa mide √(9+16)=√25=5." },
  { level: "eso", subject: "mates", q: "proporcionalidad directa e inversa", a: "Proporcionalidad directa: si una magnitud aumenta, la otra tambien (mas horas trabajas, mas ganas). Se cumple a/b = constante. Proporcionalidad inversa: si una aumenta, la otra disminuye (mas trabajadores, menos tiempo). Se cumple a×b = constante." },
  { level: "eso", subject: "mates", q: "que es una funcion matematica", a: "Una funcion asigna a cada valor de x un unico valor de y. Se escribe y=f(x). La funcion lineal y=mx+n es una recta (m es la pendiente, n donde corta al eje Y). La funcion cuadratica y=ax²+bx+c es una parabola. Se representan en un plano cartesiano con ejes X e Y." },
  { level: "eso", subject: "mates", q: "estadistica media mediana moda", a: "Media: suma de todos los valores dividido entre cuantos hay. Mediana: el valor central al ordenar los datos (si hay par, media de los dos centrales). Moda: el valor que mas se repite. Ejemplo: datos 2,3,3,5,7 → media=4, mediana=3, moda=3." },
  { level: "eso", subject: "mates", q: "probabilidad concepto y calculo", a: "La probabilidad mide la posibilidad de que ocurra un evento. P = casos favorables / casos posibles. Va de 0 (imposible) a 1 (seguro). Al lanzar un dado: P(sacar 3) = 1/6 ≈ 0.167 = 16.7%. P(sacar par) = 3/6 = 1/2 = 50%." },
  { level: "eso", subject: "mates", q: "trigonometria basica seno coseno tangente", a: "En un triangulo rectangulo: seno = cateto opuesto / hipotenusa, coseno = cateto adyacente / hipotenusa, tangente = cateto opuesto / cateto adyacente. Para un angulo de 30°: sen30°=0.5, cos30°=0.866, tan30°=0.577. Se usa para calcular lados y angulos de triangulos." },
  { level: "eso", subject: "mates", q: "areas y volumenes de figuras", a: "Areas: cuadrado=l², rectangulo=b×h, triangulo=b×h/2, circulo=π×r². Volumenes: cubo=l³, prisma=area_base×h, cilindro=π×r²×h, esfera=4/3×π×r³, cono=1/3×π×r²×h, piramide=1/3×area_base×h." },

  // ── Lengua y Literatura ESO ──────────────────────────────────
  { level: "eso", subject: "lengua", q: "analisis morfologico de palabras", a: "Analizar morfologicamente es clasificar cada palabra: sustantivo (genero, numero), adjetivo (grado), verbo (conjugacion, tiempo, modo, persona), pronombre (tipo), determinante (tipo), adverbio, preposicion, conjuncion. Ejemplo: 'Los ninos corren rapidamente' → det+sust+verbo+adv." },
  { level: "eso", subject: "lengua", q: "analisis sintactico oracion simple", a: "Sujeto: quien realiza la accion (nucleo = sustantivo/pronombre). Predicado: lo que se dice del sujeto. Complementos: CD (complemento directo: ¿que?), CI (complemento indirecto: ¿a quien?), CC (circunstancial: lugar, tiempo, modo), Atributo (con ser/estar). Ejemplo: 'Mi hermano lee libros en casa' → SN sujeto + SV predicado(nucleo verbal+CD+CCLugar)." },
  { level: "eso", subject: "lengua", q: "oraciones compuestas coordinadas subordinadas", a: "Coordinadas: dos oraciones unidas al mismo nivel por conjunciones. Tipos: copulativas (y, ni), disyuntivas (o, u), adversativas (pero, sino), explicativas (es decir). Subordinadas: una depende de la otra. Tipos: sustantivas (que+oracion), adjetivas (que/quien relativo), adverbiales (cuando, porque, si)." },
  { level: "eso", subject: "lengua", q: "generos literarios", a: "Narrativo: cuenta historias (novela, cuento, fabula, leyenda). Lirico: expresa sentimientos en verso (poesia, oda, elegia, soneto). Dramatico: para representar en teatro (comedia, tragedia, tragicomedia, entremes). Tambien existe el genero didactico (ensayo, articulo)." },
  { level: "eso", subject: "lengua", q: "figuras retoricas literarias", a: "Metafora: identificar algo con otra cosa (tus ojos son estrellas). Simil: comparar con 'como' (blanco como la nieve). Hiperbole: exagerar (te lo he dicho mil veces). Personificacion: dar cualidades humanas a cosas (el viento susurra). Anafora: repetir al inicio (verde que te quiero verde). Antitesis: oponer ideas (es tan corto el amor y tan largo el olvido)." },
  { level: "eso", subject: "lengua", q: "literatura medieval espanola", a: "Cantar de Mio Cid (s.XII): primer gran poema epico castellano, narra las hazanas de Rodrigo Diaz de Vivar. Mester de clerecia: Gonzalo de Berceo, Arcipreste de Hita (Libro de Buen Amor). Prosa: Alfonso X el Sabio, Don Juan Manuel (El Conde Lucanor). Teatro: La Celestina (Fernando de Rojas, 1499)." },
  { level: "eso", subject: "lengua", q: "renacimiento literatura espanola", a: "Siglo XVI, inspirado en la cultura grecolatina. Poesia: Garcilaso de la Vega (sonetos de amor, naturaleza idealizada). Prosa: Lazarillo de Tormes (1554, primera novela picaresca, critica social desde un antihéroe). Mistica: Santa Teresa de Jesus, San Juan de la Cruz." },
  { level: "eso", subject: "lengua", q: "barroco literatura espanola siglo de oro", a: "Siglo XVII, epoca de contrastes y pesimismo. Poesia: Quevedo (conceptismo, juegos de ideas) y Gongora (culteranismo, lenguaje ornamentado). Prosa: Cervantes con Don Quijote de la Mancha (1605-1615), la primera novela moderna. Teatro: Lope de Vega (Fuenteovejuna) y Calderon de la Barca (La vida es sueno)." },
  { level: "eso", subject: "lengua", q: "textos argumentativos y expositivos", a: "Texto expositivo: informa de forma objetiva sobre un tema (articulo enciclopedico, libro de texto). Estructura: introduccion, desarrollo, conclusion. Texto argumentativo: defiende una opinion con razones (editorial, ensayo, debate). Estructura: tesis (idea), argumentos (razones), conclusion." },
  { level: "eso", subject: "lengua", q: "que es un texto periodistico tipos", a: "Los textos periodisticos informan sobre actualidad. Generos informativos: noticia (objetiva, responde que, quien, cuando, donde, por que), reportaje. Generos de opinion: editorial, articulo de opinion, columna, carta al director. Generos mixtos: cronica, entrevista, critica." },

  // ── Biología y Geología ESO ──────────────────────────────────
  { level: "eso", subject: "biologia", q: "celula procariota y eucariota diferencias", a: "Procariota: sin nucleo definido, ADN suelto en el citoplasma, mas simple y pequena (bacterias). Eucariota: tiene nucleo con membrana que protege el ADN, organulos especializados (mitocondrias, reticulo, Golgi). Las celulas animales y vegetales son eucariotas." },
  { level: "eso", subject: "biologia", q: "celula animal y vegetal diferencias", a: "Ambas son eucariotas, pero la celula vegetal tiene: pared celular rigida (de celulosa), cloroplastos (para la fotosintesis) y una gran vacuola central. La celula animal no tiene pared celular, no tiene cloroplastos y tiene centriolos para la division celular." },
  { level: "eso", subject: "biologia", q: "mitosis y meiosis division celular", a: "Mitosis: la celula se divide en 2 celulas identicas con el mismo ADN (46 cromosomas en humanos). Sirve para crecer y reparar tejidos. Meiosis: produce 4 celulas con la mitad de cromosomas (23), los gametos (ovulos y espermatozoides). Permite la reproduccion sexual y la variabilidad genetica." },
  { level: "eso", subject: "biologia", q: "tejidos del cuerpo humano", a: "Tejido epitelial: cubre superficies (piel, mucosas). Tejido conectivo: une y sostiene (hueso, cartilago, sangre, grasa). Tejido muscular: permite el movimiento (esqueletico, cardiaco, liso). Tejido nervioso: transmite impulsos electricos (neuronas). Varios tejidos forman un organo." },
  { level: "eso", subject: "biologia", q: "sistema nervioso central y periferico", a: "El sistema nervioso central (SNC) incluye el cerebro (pensamiento, memoria, sentidos), cerebelo (equilibrio, coordinacion) y medula espinal (conecta cerebro con el cuerpo). El sistema nervioso periferico son los nervios que llevan informacion desde y hacia el SNC." },
  { level: "eso", subject: "biologia", q: "sistema endocrino hormonas", a: "El sistema endocrino produce hormonas (mensajeros quimicos) que regulan el cuerpo. Glandulas principales: hipofisis (hormona del crecimiento), tiroides (metabolismo), suprarrenales (adrenalina, cortisol), pancreas (insulina para la glucosa), ovarios (estrogenos), testiculos (testosterona)." },
  { level: "eso", subject: "biologia", q: "reproduccion humana fecundacion", a: "La reproduccion humana es sexual. El espermatozoide (celula masculina) fecunda al ovulo (celula femenina) en la trompa de Falopio. Se forma un cigoto que se divide y se implanta en el utero. El embarazo dura 9 meses (40 semanas). El embrion se desarrolla hasta formar un bebe." },
  { level: "eso", subject: "biologia", q: "genetica leyes de mendel herencia", a: "Gregor Mendel (1865) descubrio las leyes de la herencia con guisantes. 1ª ley: la primera generacion es toda igual (dominante). 2ª ley: en la segunda generacion reaparece el rasgo oculto (recesivo) en proporcion 3:1. Genotipo: los genes (AA, Aa, aa). Fenotipo: como se manifiesta." },
  { level: "eso", subject: "biologia", q: "teoria de la evolucion darwin", a: "Charles Darwin (1859) propuso la seleccion natural: los individuos con caracteristicas mas ventajosas sobreviven y se reproducen mas, transmitiendo esos rasgos. Con el tiempo, las especies cambian y se adaptan al medio. Todas las especies comparten antepasados comunes." },
  { level: "eso", subject: "biologia", q: "geologia minerales y rocas tipos", a: "Minerales: sustancias naturales solidas con composicion quimica definida (cuarzo, feldespato, mica). Rocas: conjuntos de minerales. Tres tipos: igneas (del magma: granito, basalto), sedimentarias (de sedimentos: caliza, arenisca) y metamorficas (transformadas por presion/calor: marmol, pizarra)." },
  { level: "eso", subject: "biologia", q: "tectonica de placas deriva continental", a: "La litosfera (corteza terrestre) esta dividida en grandes placas que flotan sobre el manto y se mueven lentamente (cm/ano). Donde chocan se forman montanas y terremotos. Donde se separan sale magma (dorsales oceanicas). Alfred Wegener propuso la deriva continental en 1912: los continentes estuvieron unidos (Pangea)." },
  { level: "eso", subject: "biologia", q: "ecosistemas tipos y amenazas", a: "Tipos: terrestre (bosque, desierto, tundra, pradera, selva), acuatico (marino, agua dulce). Componentes: biotopo (medio fisico) y biocenosis (seres vivos). Amenazas: deforestacion, contaminacion, cambio climatico, especies invasoras, sobreexplotacion. La biodiversidad es esencial para el equilibrio del planeta." },

  // ── Física y Química ESO ─────────────────────────────────────
  { level: "eso", subject: "fisica", q: "atomo estructura protones neutrones electrones", a: "El atomo es la unidad basica de la materia. Tiene un nucleo con protones (carga +) y neutrones (sin carga), y electrones (carga -) girando alrededor en capas. El numero atomico (Z) es el numero de protones y define el elemento. Ejemplo: el carbono tiene Z=6 (6 protones)." },
  { level: "eso", subject: "fisica", q: "tabla periodica de los elementos", a: "La tabla periodica organiza los 118 elementos quimicos por su numero atomico. Las filas son periodos (7) y las columnas son grupos (18). Los elementos del mismo grupo tienen propiedades similares. Grupos importantes: alcalinos (grupo 1), halogenos (grupo 17), gases nobles (grupo 18). Creada por Mendeleiev en 1869." },
  { level: "eso", subject: "fisica", q: "enlace ionico covalente metalico", a: "Enlace ionico: un atomo cede electrones a otro, formando iones + y - que se atraen (NaCl, sal). Enlace covalente: los atomos comparten electrones (H2O, CO2). Enlace metalico: los electrones se mueven libremente entre atomos metalicos (hierro, cobre), dando conductividad." },
  { level: "eso", subject: "fisica", q: "reacciones quimicas tipos", a: "En una reaccion quimica, unas sustancias (reactivos) se transforman en otras (productos). La masa se conserva (ley de Lavoisier). Tipos: sintesis (A+B→AB), descomposicion (AB→A+B), combustion (con O2, produce CO2 y H2O), oxidacion (metal+O2→oxido), acido-base (neutralizacion)." },
  { level: "eso", subject: "fisica", q: "leyes de newton del movimiento", a: "1ª ley (inercia): un cuerpo permanece en reposo o movimiento rectilineo uniforme si no actua ninguna fuerza. 2ª ley: F=m×a (la fuerza es masa por aceleracion). 3ª ley (accion-reaccion): toda fuerza tiene otra igual y opuesta. Ejemplo: al saltar, empujas el suelo y el suelo te empuja a ti." },
  { level: "eso", subject: "fisica", q: "energia cinetica y potencial", a: "Energia cinetica: la que tiene un cuerpo por moverse. Ec = 1/2 × m × v². A mas masa o velocidad, mas energia. Energia potencial: la almacenada por posicion. Ep = m × g × h (gravitatoria). Un objeto alto tiene mucha Ep; al caer se convierte en Ec. La energia total se conserva." },
  { level: "eso", subject: "fisica", q: "electricidad ley de ohm circuitos", a: "La corriente electrica es el flujo de electrones por un conductor. Ley de Ohm: V = I × R (voltaje = intensidad × resistencia). V se mide en voltios, I en amperios, R en ohmios. Circuito en serie: la corriente pasa por todos los componentes. En paralelo: la corriente se divide por varias ramas." },
  { level: "eso", subject: "fisica", q: "ondas sonido y luz", a: "Las ondas transportan energia sin transportar materia. Sonido: onda mecanica que necesita un medio (aire, agua); velocidad en aire ≈ 340 m/s. Luz: onda electromagnetica que puede viajar en el vacio; velocidad = 300.000 km/s. Propiedades: longitud de onda, frecuencia (Hz), amplitud." },
  { level: "eso", subject: "fisica", q: "calor y temperatura diferencia", a: "Temperatura: medida de la agitacion de las moleculas (°C, K). Calor: energia que se transfiere entre cuerpos a diferente temperatura. El calor va siempre del cuerpo caliente al frio. Se mide en julios (J) o calorias (cal). Mecanismos: conduccion, conveccion, radiacion." },
  { level: "eso", subject: "fisica", q: "formulacion quimica inorganica basica", a: "Oxidos: metal/no metal + oxigeno (Fe2O3 oxido de hierro III, CO2 dioxido de carbono). Hidruros: metal + hidrogeno (NaH hidruro de sodio). Acidos: H + no metal (HCl acido clorhidrico). Hidroxidos: metal + OH (NaOH hidroxido de sodio). Sales: metal + no metal (NaCl cloruro de sodio)." },

  // ── Geografía e Historia ESO ─────────────────────────────────
  { level: "eso", subject: "historia", q: "civilizacion griega antigua grecia", a: "Grecia antigua (s.VIII-I a.C.) creo la democracia (Atenas, Pericles), la filosofia (Socrates, Platon, Aristoteles), el teatro, los Juegos Olimpicos y grandes avances en matematicas (Pitagoras, Euclides) y ciencia. Esparta era militarista. Alejandro Magno creo un enorme imperio. Su cultura influyo en toda la civilizacion occidental." },
  { level: "eso", subject: "historia", q: "imperio romano roma antigua", a: "Roma domino el Mediterraneo durante siglos. De monarquia paso a republica (509 a.C.) y luego a imperio (27 a.C., Augusto). Aportaciones: derecho romano (base de nuestras leyes), calzadas, acueductos, latin (origen del espanol). Cayo en el 476 d.C. (parte occidental) por invasiones barbaras y crisis interna." },
  { level: "eso", subject: "historia", q: "edad media feudalismo", a: "Tras caer Roma (476), Europa se organizo con el feudalismo: el rey concedia tierras (feudos) a los nobles, que a cambio daban proteccion militar. Los campesinos (siervos) trabajaban la tierra y debian obediencia al senor feudal. La sociedad se dividia en nobleza, clero y campesinos. La Iglesia tenia enorme poder." },
  { level: "eso", subject: "historia", q: "renacimiento siglos XV XVI", a: "El Renacimiento (s.XV-XVI) fue un renacer de la cultura clasica grecolatina desde Italia. Se puso al ser humano en el centro (humanismo). Artistas: Leonardo da Vinci (Mona Lisa), Miguel Angel (Capilla Sixtina), Rafael. Inventos: la imprenta de Gutenberg (1440) revoluciono el conocimiento. Copérnico propuso el heliocentrismo." },
  { level: "eso", subject: "historia", q: "descubrimientos geograficos siglo XV XVI", a: "Portugal y Espana lideraron la exploracion. Bartolome Dias (cabo de Buena Esperanza, 1488), Colon (America, 1492), Vasco de Gama (ruta maritima a la India, 1498), Magallanes-Elcano (primera vuelta al mundo, 1519-1522). Consecuencias: intercambio de productos, colonizacion, mestizaje, choque cultural." },
  { level: "eso", subject: "historia", q: "revolucion francesa 1789", a: "En 1789, el pueblo frances, harto de la desigualdad y la pobreza, se rebelo contra el rey Luis XVI. Toma de la Bastilla (14 julio). Se proclamaron los Derechos del Hombre: libertad, igualdad, fraternidad. Fin del Antiguo Regimen (monarquia absoluta). Luis XVI fue guillotinado. Surgio Napoleon Bonaparte." },
  { level: "eso", subject: "historia", q: "revolucion industrial siglo XVIII XIX", a: "Comenzo en Inglaterra (s.XVIII). La maquina de vapor de James Watt (1769) revoluciono la produccion. Fabricas reemplazaron talleres. Exodo rural a ciudades. Ferrocarril (1825), telegrama. Nuevas clases: burguesia (duenos de fabricas) y proletariado (obreros en condiciones duras). Surgio el movimiento obrero." },
  { level: "eso", subject: "historia", q: "primera guerra mundial 1914 1918", a: "La Gran Guerra (1914-1918) enfrento a las Potencias Centrales (Alemania, Austria-Hungria, Imperio Otomano) contra los Aliados (Francia, Reino Unido, Rusia, luego EE.UU.). Causas: nacionalismos, imperialismo, alianzas. Trincheras, 17 millones de muertos. Acabo con el Tratado de Versalles. Caida de imperios." },
  { level: "eso", subject: "historia", q: "segunda guerra mundial 1939 1945", a: "Hitler (Alemania nazi) invadio Polonia en 1939. Eje (Alemania, Italia, Japon) contra Aliados (UK, URSS, EE.UU., Francia). Holocausto: 6 millones de judios asesinados. Bomba atomica en Hiroshima y Nagasaki (1945). 60-80 millones de muertos, la guerra mas destructiva. Surgio la ONU para evitar otra guerra." },
  { level: "eso", subject: "historia", q: "guerra fria estados unidos urss", a: "Tras la IIGM, el mundo se dividio en dos bloques: capitalista (EE.UU., OTAN) y comunista (URSS, Pacto de Varsovia). Nunca hubo guerra directa, pero si conflictos indirectos (Corea, Vietnam, Cuba), carrera armamentistica y espacial. Muro de Berlin (1961-1989). La URSS se disolvio en 1991." },
  { level: "eso", subject: "historia", q: "geografia de europa relieve y rios", a: "Europa tiene grandes llanuras (llanura europea del norte), cadenas montanosas (Alpes, Pirineos, Carpatos, Urales), peninsulas (Iberica, Italica, Balcanica, Escandinava). Rios principales: Volga (el mas largo, 3690 km), Danubio (atraviesa 10 paises), Rin, Sena, Tamesis." },
  { level: "eso", subject: "historia", q: "climas del mundo tipos", a: "Ecuatorial: calido y lluvioso todo el ano (selva amazonica). Tropical: calido con estacion seca y humeda (sabana). Desertico: muy seco, gran amplitud termica (Sahara). Mediterraneo: veranos secos y calurosos. Oceanico: lluvias todo el ano, temperaturas suaves. Continental: inviernos muy frios. Polar: frio extremo." },
  { level: "eso", subject: "historia", q: "globalizacion que es consecuencias", a: "La globalizacion es la interconexion mundial de economias, culturas y comunicaciones, acelerada por internet y el transporte. Ventajas: acceso a productos de todo el mundo, intercambio cultural, comunicacion instantanea. Desventajas: desigualdad entre paises, perdida de culturas locales, problemas medioambientales, deslocalizacion de empresas." },

  // ── Tecnología ESO ───────────────────────────────────────────
  { level: "eso", subject: "tecnologia", q: "materiales propiedades tipos", a: "Maderas: naturales, faciles de trabajar (pino, roble). Metales: resistentes, conductores (hierro, acero, aluminio, cobre). Plasticos: ligeros, moldeables (PET, PVC, polietileno). Ceramicos: duros, fragiles (ladrillos, porcelana). Textiles: flexibles (algodon, lana, poliester). Propiedades: dureza, elasticidad, conductividad, resistencia." },
  { level: "eso", subject: "tecnologia", q: "mecanismos palancas poleas engranajes", a: "Palanca: barra rigida que gira sobre un punto fijo (fulcro). Polea: rueda acanalada con cuerda para cambiar la direccion de una fuerza. Engranaje: ruedas dentadas que transmiten movimiento rotatorio. Manivela-biela: transforma movimiento circular en lineal. Tornillo sin fin: reduce velocidad y aumenta fuerza." },
  { level: "eso", subject: "tecnologia", q: "electricidad basica circuitos componentes", a: "Componentes: generador (pila, enchufe), interruptor (abre/cierra circuito), resistencia (limita corriente), LED (emite luz), motor (produce movimiento), condensador (almacena carga). En serie: todos en una linea, si uno falla se corta todo. En paralelo: cada uno en su rama, funcionan independientemente." },
  { level: "eso", subject: "tecnologia", q: "programacion basica conceptos", a: "Un programa es un conjunto de instrucciones que ejecuta un ordenador. Conceptos clave: variables (almacenan datos), condicionales (if/else: si pasa algo, haz esto), bucles (for/while: repite una accion), funciones (bloques de codigo reutilizables), entrada/salida (recibir datos y mostrar resultados)." },
  { level: "eso", subject: "tecnologia", q: "internet como funciona redes", a: "Internet es una red mundial de ordenadores conectados. Los datos viajan en paquetes por cables, fibra optica y wifi. Cada dispositivo tiene una IP (direccion unica). DNS traduce nombres de dominio (google.com) a IPs. Protocolos: HTTP/HTTPS (web), SMTP (email), FTP (archivos). El navegador solicita paginas a servidores." },
  { level: "eso", subject: "tecnologia", q: "robotica componentes basicos", a: "Un robot tiene: sensores (reciben informacion del entorno: luz, distancia, temperatura), actuadores (producen movimiento: motores, servos), controlador (cerebro: Arduino, microprocesador) y programa (instrucciones). Los robots industriales ensamblan coches. Los drones son robots voladores. La IA esta haciendo robots mas inteligentes." },

  // ── Inglés ESO ───────────────────────────────────────────────
  { level: "eso", subject: "ingles", q: "present perfect en ingles", a: "El present perfect conecta pasado con presente. Se forma con have/has + participio pasado. 'I have visited Paris' (He visitado Paris, la experiencia importa). 'She has lived here for 5 years' (lleva 5 anos aqui). Palabras clave: ever, never, already, yet, just, since, for." },
  { level: "eso", subject: "ingles", q: "past continuous en ingles", a: "El past continuous describe una accion en progreso en el pasado. Se forma con was/were + verbo-ing. 'I was studying when the phone rang' (Estaba estudiando cuando sono el telefono). Se usa con past simple para interrupciones: accion larga (past continuous) + accion corta (past simple)." },
  { level: "eso", subject: "ingles", q: "futuro en ingles will going to", a: "Will: predicciones, decisiones espontaneas, promesas. 'It will rain tomorrow'. 'I'll help you'. Going to: planes decididos, predicciones con evidencia. 'I'm going to study medicine'. 'Look at those clouds, it's going to rain'. Present continuous: planes fijos con fecha. 'I'm meeting John at 5'." },
  { level: "eso", subject: "ingles", q: "condicionales en ingles conditionals", a: "Zero: verdades generales (If you heat water, it boils). First: posible/probable (If it rains, I will stay home). Second: improbable/imaginario (If I won the lottery, I would travel). Third: pasado irreal (If I had studied, I would have passed). Mixed: pasado irreal + resultado presente." },
  { level: "eso", subject: "ingles", q: "voz pasiva en ingles passive voice", a: "La voz pasiva enfoca la accion, no quien la hace. Activa: 'Shakespeare wrote Hamlet'. Pasiva: 'Hamlet was written by Shakespeare'. Estructura: sujeto + be + participio pasado (+ by + agente). Se usa cuando el agente es desconocido o no importa: 'The window was broken'." },
  { level: "eso", subject: "ingles", q: "reported speech estilo indirecto ingles", a: "Al contar lo que alguien dijo, cambian los tiempos. Present→Past: 'I like pizza' → He said he liked pizza. Will→Would: 'I will come' → She said she would come. Can→Could. Tambien cambian pronombres y referencias de tiempo: today→that day, here→there, this→that." },
  { level: "eso", subject: "ingles", q: "relative clauses en ingles oraciones de relativo", a: "Las relative clauses dan informacion extra sobre un nombre. Who: personas (The girl who called is my sister). Which: cosas (The book which I read was great). That: personas y cosas (informal). Where: lugares. When: tiempo. Whose: posesion (The man whose car is red)." },
  { level: "eso", subject: "ingles", q: "verbos modales en ingles modal verbs", a: "Can: habilidad (I can swim). Could: habilidad pasada, peticion educada. Must: obligacion fuerte (You must wear a helmet). Should: consejo (You should rest). May/Might: posibilidad (It may rain). Would: condicional, peticion. Have to: obligacion externa. Don't have to: no es necesario." },
];

// ════════════════════════════════════════════════════════════════
//  BACHILLERATO  (16 – 18 años)
// ════════════════════════════════════════════════════════════════

const BACHILLERATO = [

  // ── Matemáticas Bachillerato ─────────────────────────────────
  { level: "bachillerato", subject: "mates", q: "matrices y determinantes", a: "Una matriz es una tabla de numeros organizada en filas y columnas. Se suman elemento a elemento. Producto: fila×columna. Determinante: un numero asociado a matrices cuadradas. Para 2×2: |a b; c d| = ad-bc. Si det≠0 la matriz tiene inversa. Se usan para resolver sistemas de ecuaciones (Cramer)." },
  { level: "bachillerato", subject: "mates", q: "sistemas de ecuaciones gauss cramer", a: "Metodo de Gauss: se transforma la matriz ampliada en escalonada mediante operaciones de fila para resolver el sistema. Regla de Cramer: xi = det(Ai)/det(A), sustituyendo la columna i por los terminos independientes. Clasificacion: compatible determinado (solucion unica), indeterminado (infinitas), incompatible (ninguna)." },
  { level: "bachillerato", subject: "mates", q: "limites concepto y calculo", a: "El limite de f(x) cuando x tiende a a es el valor al que se acerca f(x). lim(x→2) x² = 4. Indeterminaciones: 0/0 (factorizar o L'Hôpital), ∞/∞ (dividir por mayor potencia), ∞-∞ (operar). Limites al infinito determinan asintotas. Son la base del calculo diferencial." },
  { level: "bachillerato", subject: "mates", q: "derivadas concepto reglas aplicaciones", a: "La derivada mide la tasa de cambio instantanea (pendiente de la tangente). f'(x) = lim(h→0) [f(x+h)-f(x)]/h. Reglas: (xⁿ)'=nxⁿ⁻¹, (ef)'=ef·f', (ln f)'=f'/f, cadena, producto, cociente. Aplicaciones: maximos/minimos (f'=0), monotonia (f'>0 crece), curvatura (f'' concavidad), optimizacion." },
  { level: "bachillerato", subject: "mates", q: "integrales concepto calculo", a: "La integral es la operacion inversa de la derivada. ∫xⁿdx = xⁿ⁺¹/(n+1)+C. Integral definida: calcula el area bajo la curva entre dos puntos (Teorema Fundamental del Calculo). Metodos: sustitucion, por partes (∫udv=uv-∫vdu). Aplicaciones: areas, volumenes de revolucion, distancia, trabajo." },
  { level: "bachillerato", subject: "mates", q: "probabilidad distribucion binomial normal", a: "Distribucion binomial B(n,p): n ensayos independientes con probabilidad p de exito. P(X=k) = C(n,k)·p^k·(1-p)^(n-k). Media=np, varianza=np(1-p). Distribucion normal N(μ,σ): campana de Gauss, simetrica. El 68% de datos estan a ±1σ de la media, el 95% a ±2σ, el 99.7% a ±3σ. Se tipifica con Z=(X-μ)/σ." },
  { level: "bachillerato", subject: "mates", q: "geometria analitica vectores rectas planos", a: "Vector: segmento con direccion y sentido, v=(a,b,c). Operaciones: suma, producto escalar (u·v=|u||v|cosθ), producto vectorial (u×v, perpendicular a ambos). Recta: punto+vector director, r=(p)+t(v). Plano: punto+2 vectores o ecuacion ax+by+cz+d=0. Posiciones relativas: paralelas, secantes, coincidentes." },
  { level: "bachillerato", subject: "mates", q: "numeros complejos operaciones", a: "Los numeros complejos incluyen la unidad imaginaria i=√(-1). Forma: z=a+bi (a parte real, b parte imaginaria). Suma: (a+bi)+(c+di)=(a+c)+(b+d)i. Producto: (a+bi)(c+di)=(ac-bd)+(ad+bc)i. Modulo: |z|=√(a²+b²). Forma polar: z=r(cosθ+i·senθ). Resuelven ecuaciones como x²+1=0." },
  { level: "bachillerato", subject: "mates", q: "logaritmos propiedades", a: "El logaritmo es la operacion inversa de la potencia: log_b(x)=n significa bⁿ=x. Propiedades: log(a·b)=log(a)+log(b), log(a/b)=log(a)-log(b), log(aⁿ)=n·log(a), log_b(1)=0, log_b(b)=1. Cambio de base: log_b(x)=ln(x)/ln(b). El logaritmo natural (ln) tiene base e≈2.718." },
  { level: "bachillerato", subject: "mates", q: "sucesiones y series progresiones", a: "Progresion aritmetica: diferencia constante. an=a1+(n-1)d. Suma: Sn=n(a1+an)/2. Progresion geometrica: razon constante. an=a1·rⁿ⁻¹. Suma finita: Sn=a1(1-rⁿ)/(1-r). Suma infinita (|r|<1): S=a1/(1-r). Ejemplo: 1+1/2+1/4+1/8+...=2." },
  { level: "bachillerato", subject: "mates", q: "continuidad de funciones tipos discontinuidad", a: "Una funcion es continua en un punto si: existe f(a), existe el limite en a, y ambos son iguales. Discontinuidad evitable: el limite existe pero ≠f(a). De salto finito: los limites laterales son diferentes. De salto infinito: algun limite lateral es ±∞. Teoremas: Bolzano (si cambia de signo, hay raiz) y Weierstrass (continua en [a,b] tiene maximo y minimo)." },

  // ── Física Bachillerato ──────────────────────────────────────
  { level: "bachillerato", subject: "fisica", q: "cinematica mru mrua ecuaciones", a: "MRU (velocidad constante): x=x0+v·t. MRUA (aceleracion constante): v=v0+a·t, x=x0+v0·t+½a·t², v²=v0²+2a·Δx. Caida libre: a=g=9.8 m/s². Tiro vertical: sube decelerando, baja acelerando. Las ecuaciones se aplican componente a componente." },
  { level: "bachillerato", subject: "fisica", q: "tiro parabolico movimiento de proyectiles", a: "Un proyectil lanzado con angulo tiene movimiento horizontal (MRU) y vertical (MRUA con g). x=v0·cosθ·t, y=v0·senθ·t-½g·t². Alcance maximo con θ=45°. La trayectoria es una parabola. El tiempo de vuelo depende de la componente vertical. Ejemplo: un balon de futbol chutado con angulo." },
  { level: "bachillerato", subject: "fisica", q: "movimiento circular uniforme", a: "MCU: trayectoria circular con velocidad angular constante (ω). Periodo T=2π/ω (tiempo de una vuelta). Frecuencia f=1/T. Velocidad lineal v=ω·r. Aceleracion centripeta ac=v²/r=ω²·r (apunta al centro). Fuerza centripeta Fc=m·ac. Ejemplo: un coche en una curva, la Luna orbitando la Tierra." },
  { level: "bachillerato", subject: "fisica", q: "dinamica fuerzas trabajo energia potencia", a: "Fuerza: F=m·a (Newton). Trabajo: W=F·d·cosθ (Julios). Energia cinetica: Ec=½mv². Energia potencial gravitatoria: Ep=mgh. Conservacion: Ec+Ep=constante (sin friccion). Potencia: P=W/t (Vatios). Teorema trabajo-energia: W_total=ΔEc. Fuerzas de friccion: f=μ·N." },
  { level: "bachillerato", subject: "fisica", q: "gravitacion universal ley de newton", a: "Ley de gravitacion de Newton: F=G·m1·m2/r² (G=6.674×10⁻¹¹). Toda masa atrae a toda masa. Campo gravitatorio: g=G·M/r². Velocidad orbital: v=√(G·M/r). Las leyes de Kepler describen orbitas elipticas. Energia potencial gravitatoria: Ep=-G·M·m/r. Velocidad de escape: v=√(2G·M/r)." },
  { level: "bachillerato", subject: "fisica", q: "campo electrico ley de coulomb", a: "Ley de Coulomb: F=K·q1·q2/r² (K=9×10⁹). Cargas iguales se repelen, opuestas se atraen. Campo electrico: E=F/q=K·Q/r². Potencial: V=K·Q/r. Energia potencial electrica: Ep=K·q1·q2/r. Lineas de campo salen de cargas + y entran en cargas -. Condensadores almacenan carga: C=Q/V." },
  { level: "bachillerato", subject: "fisica", q: "campo magnetico fuerza de lorentz", a: "Una carga en movimiento crea un campo magnetico (B, en Teslas). Fuerza sobre carga en movimiento: F=q·v×B (fuerza de Lorentz, perpendicular a v y B). Fuerza sobre conductor con corriente: F=I·L×B. Ley de Ampere, ley de Biot-Savart. Aplicaciones: motores electricos, generadores, electroimanes." },
  { level: "bachillerato", subject: "fisica", q: "ondas electromagnéticas espectro", a: "Las ondas EM son oscilaciones de campos electrico y magnetico que viajan a la velocidad de la luz (c=3×10⁸ m/s). Espectro (menor a mayor frecuencia): ondas de radio, microondas, infrarrojo, luz visible (rojo→violeta), ultravioleta, rayos X, rayos gamma. c=λ·f. Energia: E=h·f (Planck)." },
  { level: "bachillerato", subject: "fisica", q: "optica reflexion refraccion lentes", a: "Reflexion: angulo incidencia = angulo reflexion (espejos). Refraccion: la luz cambia de direccion al pasar entre medios (ley de Snell: n1·senθ1=n2·senθ2). Lentes convergentes: concentran luz (lupas). Divergentes: dispersan luz (miopia). El ojo humano es un sistema optico con lente (cristalino)." },
  { level: "bachillerato", subject: "fisica", q: "fisica nuclear radiactividad", a: "El nucleo tiene protones y neutrones unidos por la fuerza nuclear fuerte. Radiactividad: nucleos inestables emiten radiacion. Tipos: alfa (2p+2n, helico), beta (electron o positron), gamma (foton de alta energia). Vida media: tiempo para que decaiga la mitad. Fision: romper nucleos pesados (centrales nucleares). Fusion: unir nucleos ligeros (el Sol). E=mc²." },
  { level: "bachillerato", subject: "fisica", q: "relatividad especial einstein", a: "Einstein (1905) postulo que la velocidad de la luz es constante para todos los observadores y las leyes fisicas son iguales en todos los sistemas inerciales. Consecuencias: dilatacion del tiempo (relojes lentos a alta velocidad), contraccion de la longitud, equivalencia masa-energia E=mc². Nada puede superar la velocidad de la luz." },

  // ── Química Bachillerato ─────────────────────────────────────
  { level: "bachillerato", subject: "quimica", q: "estructura atomica modelo cuantico orbitales", a: "El modelo cuantico describe el atomo con numeros cuanticos: n (nivel energetico 1,2,3...), l (tipo de orbital: s,p,d,f), ml (orientacion) y ms (espin ±1/2). Los electrones llenan orbitales de menor a mayor energia (Aufbau): 1s 2s 2p 3s 3p 4s 3d... Principio de exclusion de Pauli: maximo 2 electrones por orbital." },
  { level: "bachillerato", subject: "quimica", q: "configuracion electronica elementos", a: "La configuracion electronica indica como se distribuyen los electrones. Ejemplo: Carbono (Z=6): 1s² 2s² 2p². Oxigeno (Z=8): 1s² 2s² 2p⁴. Hierro (Z=26): [Ar] 3d⁶ 4s². Los electrones de valencia (capa mas externa) determinan las propiedades quimicas y los enlaces que forma un elemento." },
  { level: "bachillerato", subject: "quimica", q: "propiedades periodicas electronegatividad", a: "Las propiedades periodicas varian con la posicion en la tabla. Radio atomico: aumenta hacia abajo y a la izquierda. Energia de ionizacion (arrancar un electron): aumenta hacia arriba y derecha. Electronegatividad (atraer electrones en un enlace): aumenta hacia arriba y derecha (fluor es el mas electronegativo)." },
  { level: "bachillerato", subject: "quimica", q: "termodinamica quimica entalpia entropia", a: "Entalpia (H): calor a presion constante. Reaccion exotermica: ΔH<0 (libera calor). Endotermica: ΔH>0. Entropia (S): medida del desorden, tiende a aumentar. Energia libre de Gibbs: ΔG=ΔH-TΔS. Si ΔG<0 la reaccion es espontanea. Ley de Hess: ΔH total = suma de ΔH de cada paso." },
  { level: "bachillerato", subject: "quimica", q: "cinetica quimica velocidad de reaccion", a: "La cinetica estudia la velocidad de las reacciones. Factores que la aumentan: mayor temperatura (mas choques), mayor concentracion, mayor superficie de contacto, catalizadores (bajan la energia de activacion sin consumirse). Ecuacion de Arrhenius: k=A·e^(-Ea/RT). Orden de reaccion: v=k[A]^n[B]^m." },
  { level: "bachillerato", subject: "quimica", q: "equilibrio quimico le chatelier", a: "En equilibrio, la velocidad directa = inversa. Constante de equilibrio: Kc=[productos]/[reactivos] (elevados a sus coeficientes). Principio de Le Chatelier: si se perturba un equilibrio, se desplaza para contrarrestar el cambio. Anadir reactivo→desplaza a productos. Aumentar T en exotermica→desplaza a reactivos." },
  { level: "bachillerato", subject: "quimica", q: "acidos y bases ph escala", a: "Acido: dona H⁺ (Brønsted). Base: acepta H⁺. pH = -log[H⁺]. pH<7 acido, pH=7 neutro, pH>7 basico. Acidos fuertes (HCl, HNO3) se disocian totalmente. Debiles (CH3COOH) parcialmente (Ka). Neutralizacion: acido+base→sal+agua. Tampones/buffer mantienen el pH estable." },
  { level: "bachillerato", subject: "quimica", q: "reacciones redox oxidacion reduccion", a: "Oxidacion: perder electrones (aumenta nº de oxidacion). Reduccion: ganar electrones (disminuye). Agente oxidante: se reduce (gana e⁻). Agente reductor: se oxida (pierde e⁻). Ajuste redox: igualar electrones ganados y perdidos. Pilas: reaccion redox espontanea genera electricidad. Electrolisis: forzar reaccion no espontanea con electricidad." },
  { level: "bachillerato", subject: "quimica", q: "quimica organica hidrocarburos alcoholes", a: "La quimica organica estudia compuestos de carbono. Hidrocarburos: solo C y H. Alcanos (enlace simple: metano CH4, etano), alquenos (doble enlace: eteno), alquinos (triple: etino). Grupos funcionales: alcohol (-OH: etanol), aldehido (-CHO), cetona (C=O), acido carboxilico (-COOH: vinagre), ester, amina, amida." },
  { level: "bachillerato", subject: "quimica", q: "estequiometria calculos quimicos", a: "La estequiometria calcula cantidades en reacciones. Se usan moles (1 mol = 6.022×10²³ particulas = masa molar en gramos). Pasos: 1) Ajustar la ecuacion, 2) Convertir datos a moles, 3) Usar proporcion de coeficientes, 4) Convertir a unidades pedidas. Reactivo limitante: el que se agota primero. Rendimiento = (real/teorico)×100%." },

  // ── Biología Bachillerato ────────────────────────────────────
  { level: "bachillerato", subject: "biologia", q: "biomoleculas glucidos lipidos proteinas acidos nucleicos", a: "Glucidos: funcion energetica (glucosa, almidon) y estructural (celulosa). Lipidos: reserva energetica (grasas), estructural (fosfolipidos de membranas), reguladora (hormonas esteroideas). Proteinas: formadas por aminoacidos, funcion enzimatica, estructural, inmunitaria. Acidos nucleicos: ADN (doble helice, informacion genetica) y ARN (simple cadena, expresion genica)." },
  { level: "bachillerato", subject: "biologia", q: "metabolismo catabolismo anabolismo atp", a: "Metabolismo es el conjunto de reacciones quimicas celulares. Catabolismo: degrada moleculas complejas en simples, liberando energia (ATP). Ejemplo: respiracion celular (glucosa+O2→CO2+H2O+38ATP). Anabolismo: construye moleculas complejas a partir de simples, gasta energia. Ejemplo: fotosintesis (CO2+H2O+luz→glucosa+O2). El ATP es la moneda energetica." },
  { level: "bachillerato", subject: "biologia", q: "respiracion celular mitocondria etapas", a: "La respiracion celular ocurre en la mitocondria y tiene 3 etapas: 1) Glucolisis (citoplasma): glucosa→2 piruvato + 2ATP. 2) Ciclo de Krebs (matriz mitocondrial): piruvato se oxida, genera NADH y FADH2. 3) Cadena de transporte de electrones (membrana interna): NADH/FADH2 ceden electrones, generando ~34ATP. Total: ~38 ATP por glucosa." },
  { level: "bachillerato", subject: "biologia", q: "fotosintesis fases clara y oscura calvin", a: "Fase luminosa (tilacoides): la luz excita clorofila, se rompe H2O (fotolisis), generando O2, ATP y NADPH. Fotosistemas I y II. Fase oscura o ciclo de Calvin (estroma): usa ATP y NADPH para fijar CO2 en glucosa. Enzima clave: RuBisCO. Balance: 6CO2+6H2O+luz → C6H12O6+6O2." },
  { level: "bachillerato", subject: "biologia", q: "genetica molecular replicacion transcripcion traduccion", a: "Replicacion: el ADN se copia (ADN polimerasa, semiconservativa, 5'→3'). Transcripcion: un gen de ADN se copia a ARNm (ARN polimerasa, en el nucleo). Traduccion: el ARNm se lee en los ribosomas, cada codon (3 bases) codifica un aminoacido, formando una proteina. Dogma central: ADN→ARN→Proteina." },
  { level: "bachillerato", subject: "biologia", q: "mutaciones tipos y consecuencias", a: "Mutaciones: cambios en el ADN. Genicas: afectan un gen (sustitucion, insercion, delecion de bases). Cromosomicas: afectan la estructura del cromosoma (delecion, duplicacion, inversion, translocacion). Genomicas: cambian el numero de cromosomas (trisomia 21 = sindrome de Down, poliploidia). Pueden ser beneficiosas, neutras o daninas. Son la materia prima de la evolucion." },
  { level: "bachillerato", subject: "biologia", q: "biotecnologia ingenieria genetica", a: "La biotecnologia usa organismos o sus componentes para producir bienes. Ingenieria genetica: modificar el ADN de un organismo. Herramientas: enzimas de restriccion (cortan ADN), ligasas (pegan), vectores (plasmidos), PCR (amplificar ADN), CRISPR (edicion precisa). Aplicaciones: transgenicos, terapia genica, produccion de insulina, test de ADN." },
  { level: "bachillerato", subject: "biologia", q: "microbiologia virus bacterias", a: "Bacterias: procariotas unicelulares, se reproducen por fision binaria. Formas: cocos (esfera), bacilos (barra), espirilos (espiral). Pueden ser beneficiosas (flora intestinal, yogur) o patogenas (tuberculosis). Virus: NO son celulas, necesitan una celula huesped para reproducirse. Tienen acido nucleico (ADN o ARN) + capside proteica. Ejemplos: gripe, COVID, VIH." },
  { level: "bachillerato", subject: "biologia", q: "inmunologia sistema inmunitario", a: "Inmunidad innata: barreras (piel, mucosas), inflamacion, fagocitos. Inmunidad adaptativa: linfocitos B (producen anticuerpos = inmunidad humoral) y linfocitos T (destruyen celulas infectadas = inmunidad celular). Memoria inmunologica: tras una infeccion, los linfocitos de memoria responden mas rapido. Las vacunas aprovechan esto: introducen antigenos debilitados para crear memoria." },
  { level: "bachillerato", subject: "biologia", q: "ecologia flujos de energia ciclos biogeoquimicos", a: "Energia: fluye en una sola direccion (sol→productores→consumidores). En cada nivel trofico se pierde ~90% como calor. Piramide de energia. Ciclos biogeoquimicos: la materia se recicla. Ciclo del carbono (fotosintesis/respiracion/combustion), nitrogeno (fijacion/nitrificacion/desnitrificacion), agua, fosforo. El ser humano altera estos ciclos (efecto invernadero, eutrofizacion)." },

  // ── Historia de España Bachillerato ──────────────────────────
  { level: "bachillerato", subject: "historia", q: "hispania romana romanizacion peninsula iberica", a: "Roma conquisto la peninsula iberica entre los siglos III y I a.C. La romanizacion trajo: latin (origen del espanol), derecho romano, obras publicas (calzadas, acueductos como el de Segovia, teatros como el de Merida), urbanismo, el cristianismo. Hispania fue una de las provincias mas importantes del Imperio, dio emperadores como Trajano y Adriano." },
  { level: "bachillerato", subject: "historia", q: "al andalus y reinos cristianos medievales", a: "En 711, los musulmanes cruzaron el estrecho y conquistaron casi toda la peninsula. Al-Andalus alcanzo su maximo esplendor con el Califato de Cordoba (s.X). Aportaciones: algebra, regadio, arquitectura (Alhambra, Mezquita de Cordoba). Los reinos cristianos (Castilla, Aragon, Navarra, Portugal) avanzaron hacia el sur (Reconquista). Convivencia de tres culturas: cristiana, musulmana y judia." },
  { level: "bachillerato", subject: "historia", q: "reyes catolicos unificacion espana", a: "Isabel de Castilla y Fernando de Aragon se casaron en 1469, uniendo sus coronas. Logros: toma de Granada (1492, fin de la Reconquista), descubrimiento de America (Colon), expulsion de los judios (1492), Inquisicion, unificacion religiosa. Sentaron las bases del Estado moderno espanol." },
  { level: "bachillerato", subject: "historia", q: "imperio espanol siglo de oro habsburgo", a: "Con Carlos I (1516) y Felipe II, Espana fue la potencia mas poderosa del mundo. Imperio en Europa (Paises Bajos, Italia, Alemania) y America. Siglo de Oro cultural: Cervantes, Lope de Vega, Velazquez, El Greco. La Armada Invencible fracaso contra Inglaterra (1588). Decadencia con Felipe III y IV por guerras constantes y crisis economica." },
  { level: "bachillerato", subject: "historia", q: "siglo XVIII borbones ilustracion espana", a: "Tras la Guerra de Sucesion (1700-1714), los Borbones reemplazaron a los Habsburgo. Felipe V centralizo el poder (Decretos de Nueva Planta, eliminaron fueros de Aragon). Carlos III fue el rey ilustrado: reformas economicas, obras publicas en Madrid (Puerta de Alcala, Prado). La Ilustracion trajo ideas de razon, progreso y educacion." },
  { level: "bachillerato", subject: "historia", q: "guerra de la independencia espanola 1808", a: "Napoleon invadio Espana y puso a su hermano Jose I como rey (1808). El pueblo se levanto el 2 de mayo de 1808 en Madrid. Guerra de guerrillas contra los franceses. Las Cortes de Cadiz redactaron la primera Constitucion espanola (La Pepa, 1812): soberania nacional, division de poderes, libertad de prensa. Fernando VII la derogo al volver (1814)." },
  { level: "bachillerato", subject: "historia", q: "siglo XIX espana constituciones y conflictos", a: "El siglo XIX espanol fue muy inestable: alternancia entre liberales y absolutistas, tres guerras carlistas, pronunciamientos militares, seis constituciones. Isabel II (1833-1868) fue derrocada. Sexenio Democratico (1868-1874): Primera Republica breve. Restauracion borbonica (1874): Alfonso XII, sistema de turnos (Canovas/Sagasta), caciquismo." },
  { level: "bachillerato", subject: "historia", q: "crisis del 98 perdida de colonias", a: "En 1898, Espana perdio sus ultimas colonias (Cuba, Puerto Rico, Filipinas) tras la guerra contra EE.UU. Causo una profunda crisis de identidad nacional. La Generacion del 98 (Unamuno, Machado, Baroja, Valle-Inclan) reflexiono sobre Espana. Regeneracionismo: Joaquin Costa propuso modernizar el pais ('escuela y despensa')." },
  { level: "bachillerato", subject: "historia", q: "segunda republica espanola 1931", a: "Proclamada el 14 de abril de 1931 tras la victoria republicana en elecciones municipales. Reformas: Constitucion de 1931 (laica, sufragio universal incluido femenino), reforma agraria, educacion publica, Estatuto de autonomia de Cataluna. Tension entre izquierda y derecha. Bienio reformista (1931-33), bienio conservador (1933-36), Frente Popular (1936)." },
  { level: "bachillerato", subject: "historia", q: "guerra civil espanola 1936 1939", a: "Comenzo con el golpe militar del 18 de julio de 1936 contra la Republica. Bando republicano (gobierno legitimo, apoyo de URSS, Brigadas Internacionales) vs bando nacional (Franco, apoyo de Alemania nazi e Italia fascista). Bombardeo de Guernica (1937). Madrid resistio hasta el final. Acabo el 1 de abril de 1939 con victoria de Franco. ~500.000 muertos, exilio masivo." },
  { level: "bachillerato", subject: "historia", q: "franquismo dictadura 1939 1975", a: "Francisco Franco goberno como dictador de 1939 a 1975. Autarquia economica inicial, represion politica, censura, partido unico (Movimiento Nacional). Anos 40-50: hambre y aislamiento. Desde 1959: Plan de Estabilizacion, desarrollismo economico, turismo, emigracion. Sin libertades politicas ni sindicales. Oposicion creciente en los anos 70." },
  { level: "bachillerato", subject: "historia", q: "transicion espanola democracia 1975 1982", a: "Tras la muerte de Franco (1975), Juan Carlos I fue proclamado rey. Adolfo Suarez piloto la transicion: legalizo partidos (incluido el PCE), convoco elecciones (1977), se aprobo la Constitucion de 1978 (monarquia parlamentaria, estado de las autonomias). Intento de golpe de Estado el 23-F (1981). Victoria del PSOE (Felipe Gonzalez) en 1982 consolido la democracia." },
  { level: "bachillerato", subject: "historia", q: "espana en la union europea y actualidad", a: "Espana entro en la CEE (hoy UE) el 1 de enero de 1986. Beneficios: fondos europeos, modernizacion de infraestructuras, libre circulacion. Adopcion del euro en 2002. Eventos: JJOO Barcelona 1992, Expo Sevilla 1992, crisis economica 2008, movimiento 15-M (2011), crisis catalana (2017), pandemia COVID-19 (2020)." },

  // ── Filosofía Bachillerato ───────────────────────────────────
  { level: "bachillerato", subject: "filosofia", q: "presocraticos origen de la filosofia griega", a: "Los presocraticos (s.VI-V a.C.) buscaron el principio (arje) de todas las cosas mediante la razon, no el mito. Tales: el agua. Anaximandro: lo indefinido (apeiron). Heraclito: el cambio constante ('todo fluye'). Parmenides: el ser es inmovil y eterno. Democrito: los atomos. Pitagoras: los numeros. Fueron los primeros filosofos de Occidente." },
  { level: "bachillerato", subject: "filosofia", q: "socrates platon aristoteles filosofia clasica", a: "Socrates: el dialogo y la mayeutica ('solo se que no se nada'). Platon: mundo de las Ideas (la realidad verdadera es inmaterial), alegoria de la caverna, alma inmortal, Estado ideal gobernado por filosofos. Aristoteles: empirismo, logica formal, las 4 causas (material, formal, eficiente, final), etica del termino medio, politica como ciencia." },
  { level: "bachillerato", subject: "filosofia", q: "filosofia medieval tomas de aquino", a: "La filosofia medieval busco conciliar fe y razon. San Agustin (s.V): influencia platonica, la verdad esta en el interior del hombre. Santo Tomas de Aquino (s.XIII): fusiono aristotelismo con cristianismo. 5 vias para demostrar la existencia de Dios (movimiento, causa, contingencia, grados de perfeccion, orden del universo). Debate universales: realismo vs nominalismo (Guillermo de Ockham)." },
  { level: "bachillerato", subject: "filosofia", q: "racionalismo descartes", a: "Rene Descartes (1596-1650), padre del racionalismo moderno. Metodo de la duda: duda de todo hasta encontrar algo indudable. 'Pienso, luego existo' (cogito ergo sum). La razon es la fuente del conocimiento, no los sentidos. Dualismo: mente (res cogitans) y cuerpo (res extensa) son sustancias distintas. Ideas innatas." },
  { level: "bachillerato", subject: "filosofia", q: "empirismo hume locke", a: "El empirismo afirma que todo conocimiento viene de la experiencia sensorial. John Locke: la mente es una 'tabula rasa' (hoja en blanco) al nacer. David Hume: critico la causalidad (solo vemos sucesion, no conexion necesaria), el problema de la induccion, escepticismo. No hay ideas innatas; sin experiencia no hay conocimiento." },
  { level: "bachillerato", subject: "filosofia", q: "kant filosofia critica ilustracion", a: "Immanuel Kant (1724-1804) unio racionalismo y empirismo. Critica de la razon pura: el conocimiento requiere experiencia (contenido) + categorias del entendimiento (forma). No podemos conocer la 'cosa en si' (noumeno), solo como se nos aparece (fenomeno). Etica: imperativo categorico ('actua como si tu maxima fuera ley universal'). La Ilustracion: 'atrevete a pensar por ti mismo'." },
  { level: "bachillerato", subject: "filosofia", q: "marx materialismo historico", a: "Karl Marx (1818-1883) desarrollo el materialismo historico: la economia (infraestructura) determina la politica, cultura e ideas (superestructura). La historia es lucha de clases (amos/esclavos, senores/siervos, burgueses/proletarios). El capitalismo explota al obrero (plusvalia). Propuso la revolucion proletaria y la sociedad sin clases (comunismo)." },
  { level: "bachillerato", subject: "filosofia", q: "nietzsche voluntad de poder superhombre", a: "Friedrich Nietzsche (1844-1900) critico la moral judeocristiana y la metafisica tradicional. 'Dios ha muerto': fin de los valores absolutos (nihilismo). Propuso la 'voluntad de poder' como impulso vital y el superhombre (Übermensch) que crea sus propios valores. El eterno retorno: vivir como si todo se repitiera infinitamente. Perspectivismo: no hay verdad absoluta." },
  { level: "bachillerato", subject: "filosofia", q: "existencialismo sartre kierkegaard", a: "El existencialismo pone la existencia antes que la esencia: primero existimos, luego nos definimos con nuestras elecciones. Kierkegaard (precursor): la angustia ante la libertad, salto de fe. Jean-Paul Sartre: 'el hombre esta condenado a ser libre', somos totalmente responsables de nuestras acciones, la mala fe es huir de esa libertad. Simone de Beauvoir: existencialismo feminista." },
  { level: "bachillerato", subject: "filosofia", q: "etica utilitarismo deontologia", a: "Utilitarismo (Bentham, Mill): una accion es buena si produce la mayor felicidad para el mayor numero. Se juzga por las consecuencias. Deontologia (Kant): una accion es buena si cumple el deber moral, independientemente de las consecuencias. El imperativo categorico. Etica de la virtud (Aristoteles): lo bueno es desarrollar virtudes (prudencia, justicia, valor, templanza)." },
  { level: "bachillerato", subject: "filosofia", q: "filosofia de la ciencia metodo cientifico", a: "El metodo cientifico: observacion→hipotesis→experimentacion→conclusion. Karl Popper: una teoria es cientifica si se puede falsificar (demostrar falsa). Thomas Kuhn: la ciencia avanza por revoluciones (cambios de paradigma), no acumulativamente. Ejemplo: de Newton a Einstein. El inductivismo (generalizaciones) vs deductivismo (hipotesis→deduccion→test)." },

  // ── Lengua y Literatura Bachillerato ─────────────────────────
  { level: "bachillerato", subject: "lengua", q: "comentario de texto estructura", a: "Un comentario de texto tiene: 1) Resumen (breve, objetivo). 2) Tema (idea principal en una frase). 3) Estructura (partes del texto y su funcion). 4) Caracterizacion (tipo de texto, registro, funcion del lenguaje). 5) Valoracion critica (opinion argumentada, relacion con el contexto). Se redacta de forma cohesionada, no como esquema." },
  { level: "bachillerato", subject: "lengua", q: "variedades linguisticas dialectos registros", a: "Variedades diatopicas (dialectos por zona): andaluz, canario, murciano; en Hispanoamerica: seseo, voseo. Variedades diastraticas (por nivel social): culto, coloquial, vulgar. Variedades diafasicas (por situacion): registro formal (discurso, escrito academico) e informal (conversacion entre amigos). La norma linguistica es el uso correcto aceptado." },
  { level: "bachillerato", subject: "lengua", q: "semantica pragmatica linguistica", a: "Semantica: estudio del significado. Denotacion (significado objetivo: 'perro' = animal canino) vs connotacion (significado subjetivo: 'perro' = desleal). Polisemia: una palabra, varios significados. Homonimia: palabras distintas que suenan igual. Pragmatica: significado en contexto. Actos de habla (Austin): locutivo, ilocutivo, perlocutivo. Implicaturas (Grice)." },
  { level: "bachillerato", subject: "lengua", q: "literatura medieval mio cid celestina", a: "Cantar de Mio Cid (h.1200): poema epico anonimo sobre Rodrigo Diaz de Vivar, heroe castellano. Temas: honor, lealtad, ascenso social. Mester de clerecia: Gonzalo de Berceo (Milagros de Nuestra Senora), Arcipreste de Hita (Libro de Buen Amor). Prosa: Don Juan Manuel (El Conde Lucanor). La Celestina (1499, Fernando de Rojas): tragicomedia, inicio de la modernidad." },
  { level: "bachillerato", subject: "lengua", q: "siglo de oro don quijote cervantes", a: "Miguel de Cervantes publico Don Quijote de la Mancha (1605, 1615), considerada la primera novela moderna. Parodia de las novelas de caballeria. Don Quijote (idealista, loco) y Sancho Panza (realista, practico) representan la dualidad humana. Temas: realidad vs ficcion, libertad, justicia. Influyo en toda la literatura mundial." },
  { level: "bachillerato", subject: "lengua", q: "romanticismo literario espanol", a: "El Romanticismo (1ª mitad s.XIX) exalta los sentimientos, la libertad y la naturaleza salvaje. Jose de Espronceda: poesia rebelde (Cancion del pirata). Duque de Rivas: Don Alvaro o la fuerza del sino. Gustavo Adolfo Becquer: Rimas (poesia intimista) y Leyendas (prosa fantastica). Rosalia de Castro: poesia en gallego y castellano." },
  { level: "bachillerato", subject: "lengua", q: "realismo y naturalismo literario espanol", a: "El Realismo (2ª mitad s.XIX) describe la realidad social con objetividad. Benito Perez Galdos: Fortunata y Jacinta, Episodios Nacionales. Leopoldo Alas 'Clarin': La Regenta (critica a la sociedad de Vetusta/Oviedo). Naturalismo (Emilia Pardo Bazan): influencia de Zola, determinismo biologico y social, Los Pazos de Ulloa." },
  { level: "bachillerato", subject: "lengua", q: "modernismo y generacion del 98", a: "Modernismo (Ruben Dario): renovacion estetica, musicalidad, exotismo ('Azul'). Generacion del 98: crisis por la perdida de colonias. Unamuno (Niebla, angustia existencial), Antonio Machado (Campos de Castilla, paisaje y meditacion), Valle-Inclan (esperpento: Luces de Bohemia), Baroja (El arbol de la ciencia), Azorin." },
  { level: "bachillerato", subject: "lengua", q: "generacion del 27 poesia", a: "Grupo de poetas que fusionaron tradicion y vanguardia. Federico Garcia Lorca: Romancero gitano, Poeta en Nueva York (fusilado en 1936). Rafael Alberti: Marinero en tierra. Luis Cernuda: La realidad y el deseo. Pedro Salinas: La voz a ti debida. Vicente Aleixandre (Nobel 1977). Jorge Guillen. Gerardo Diego. Damaso Alonso." },
  { level: "bachillerato", subject: "lengua", q: "literatura espanola contemporanea posguerra", a: "Posguerra: Camilo Jose Cela (La familia de Pascual Duarte, tremendismo; La colmena, realismo social; Nobel 1989). Miguel Delibes (Los santos inocentes). Carmen Laforet (Nada). Poesia social (Blas de Otero, Gabriel Celaya). Desde los 60: renovacion experimental. Novela actual: Javier Marias, Almudena Grandes, Antonio Munoz Molina, Rosa Montero." },

  // ── Inglés Bachillerato ──────────────────────────────────────
  { level: "bachillerato", subject: "ingles", q: "tiempos verbales avanzados en ingles", a: "Past perfect: had+participio (action before another past action). Past perfect continuous: had been+ing (duration before past event). Future perfect: will have+participio (completed by future time). Future continuous: will be+ing (in progress at future time). Ejemplo: 'By 2030, I will have graduated' (Para 2030, me habre graduado)." },
  { level: "bachillerato", subject: "ingles", q: "wish y condicional tercer tipo en ingles", a: "Wish+past simple: deseo presente irreal (I wish I had a car = ojala tuviera coche). Wish+past perfect: arrepentimiento (I wish I had studied = ojala hubiera estudiado). Third conditional: If+past perfect, would have+participio (If I had known, I would have come = Si hubiera sabido, habria venido)." },
  { level: "bachillerato", subject: "ingles", q: "phrasal verbs comunes en ingles", a: "Phrasal verbs = verbo + particula, significado diferente al literal. Give up (rendirse), look after (cuidar), put off (posponer), turn on/off (encender/apagar), find out (descubrir), bring up (criar/mencionar), carry on (continuar), get along with (llevarse bien), look forward to (tener ganas de), break down (averiarse)." },
  { level: "bachillerato", subject: "ingles", q: "conectores y linking words en ingles", a: "Addition: moreover, furthermore, in addition, besides. Contrast: however, nevertheless, although, despite, on the other hand. Cause: because, since, due to, owing to. Result: therefore, consequently, as a result, thus. Example: for instance, such as. Conclusion: in conclusion, to sum up, all in all." },
  { level: "bachillerato", subject: "ingles", q: "writing formal essay en ingles", a: "Estructura: Introduction (presenta el tema, tesis). Body paragraph 1 (argumento 1 + evidencia). Body paragraph 2 (argumento 2 + evidencia). Counterargument (punto de vista opuesto + refutacion). Conclusion (resumen + opinion final). Registro formal: no contracciones, no coloquialismos, linking words, pasiva. Min 200-250 palabras." },
];

// ════════════════════════════════════════════════════════════════
//  Curiosidades educativas adicionales por nivel
// ════════════════════════════════════════════════════════════════

const EDUCATION_FUN_FACTS = [
  // Primaria
  { topic: "mates", fact: "El numero cero no existia en Europa hasta que los arabes lo trajeron de la India en la Edad Media. Los romanos no tenian simbolo para el cero." },
  { topic: "mates", fact: "Un googol es un 1 seguido de 100 ceros. Google se llama asi por un error al escribir 'googol'." },
  { topic: "lengua", fact: "El espanol es el segundo idioma con mas hablantes nativos del mundo (mas de 490 millones), solo por detras del chino mandarin." },
  { topic: "lengua", fact: "La palabra mas larga del espanol aceptada por la RAE es 'electroencefalografista' con 23 letras." },
  { topic: "naturales", fact: "Un solo arbol grande produce oxigeno suficiente para que respiren 4 personas durante un ano." },
  { topic: "naturales", fact: "El animal mas fuerte proporcionalmente es el escarabajo rinoceronte: puede cargar 850 veces su peso." },
  { topic: "sociales", fact: "El metro de Madrid fue el primer metro de Espana, inaugurado en 1919 con una sola linea de 8 estaciones." },
  { topic: "sociales", fact: "Espana es el tercer pais del mundo con mas lugares Patrimonio de la Humanidad de la UNESCO (49), tras Italia y China." },
  { topic: "artistica", fact: "El Museo del Prado de Madrid tiene mas de 8.000 pinturas, pero solo unas 1.500 estan expuestas al publico." },
  // ESO
  { topic: "biologia", fact: "Si desenrollaras todo el ADN de una sola celula humana, mediria unos 2 metros. Todo el ADN de tu cuerpo llegaria al Sol y volveria mas de 600 veces." },
  { topic: "biologia", fact: "Los seres humanos compartimos el 98.7% de nuestro ADN con los chimpances y el 60% con los platanos." },
  { topic: "fisica", fact: "Si pudieras conducir un coche a 100 km/h en linea recta hacia el Sol, tardarias 171 anos en llegar." },
  { topic: "fisica", fact: "Un rayo tiene suficiente energia como para tostar 100.000 rebanadas de pan." },
  { topic: "historia", fact: "El Imperio Romano duro mas de 1000 anos si cuentas desde la fundacion de Roma (753 a.C.) hasta la caida de Constantinopla (1453)." },
  { topic: "historia", fact: "La Gran Muralla China no se ve desde el espacio a simple vista. Es un mito popular. Los astronautas lo han desmentido." },
  { topic: "tecnologia", fact: "El primer mensaje de correo electronico se envio en 1971. El primer SMS en 1992 decia 'Merry Christmas' (Feliz Navidad)." },
  // Bachillerato
  { topic: "filosofia", fact: "Socrates nunca escribio nada. Todo lo que sabemos de el lo conocemos por los escritos de su alumno Platon." },
  { topic: "filosofia", fact: "Descartes decia que pensaba mejor en la cama. Trabajaba tumbado hasta el mediodia y ahi desarrollo gran parte de su filosofia." },
  { topic: "quimica", fact: "El cuerpo humano contiene suficiente carbono para fabricar 9.000 lapices, suficiente hierro para un clavo y suficiente fosforo para 2.200 cerillas." },
  { topic: "quimica", fact: "El elemento mas abundante en el universo es el hidrogeno (75% de toda la materia visible). El segundo es el helio." },
  { topic: "literatura", fact: "Lope de Vega escribio unas 1.500 obras de teatro. Se calcula que producia una obra completa cada 2 o 3 dias." },
  { topic: "literatura", fact: "Don Quijote de la Mancha es el libro mas traducido del mundo despues de la Biblia, con versiones en mas de 140 idiomas." },
];

export { PRIMARIA, ESO, BACHILLERATO, EDUCATION_FUN_FACTS };
